### ISSUE TITLE
Cloud projection issues about Robosense-32 LiDAR

### ISSUE THREAD

**Issue by zxl19** [facontidavide/LeGO-LOAM-BOR#22]
Hi, thank you for your excellent work.
I'm using a [Robosense-32 LiDAR](https://www.robosense.ai/rslidar/rs-lidar-32). The LiDAR has 32 unevenly distributed lines, the vertical angular resolution is not constant. I wrote an implementation to project the points correctly in `imageProjection.cpp` and modified the `loam_config.yaml` file accordingly. Still, the result is poor. A lot of points are missing and the map cannot be built successfully due to the lack of features. But this implementation works well in [the original LeGO-LOAM](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM), I still can't find what seems to be the problem, can you give me a hint?

Best regards.

**Comment by zxl19** [comment]
P.S. This is my implementation in `imageProjection.cpp`:

```C++
// *Original
// int rowIdn = (verticalAngle + _ang_bottom) / _ang_resolution_Y;
// if (rowIdn < 0 || rowIdn >= _vertical_scans) {
//   continue;
// }

// *RS-LiDAR-32
int rowIdn;
int tmp = round(verticalAngle);
if (verticalAngle < 1.7 && verticalAngle > -4.7)
{
  rowIdn = round(verticalAngle / 0.333) + 20;
}
else if (tmp == 15)
{
  rowIdn = 31;
}
else if (tmp == 10)
{
  rowIdn = 30;
}
else if (tmp == 7)
{
  rowIdn = 29;
}
else if (tmp == 5)
{
  rowIdn = 28;
}
else if (tmp == 3)
{
  rowIdn = 27;
}
else if (tmp == 2 && verticalAngle > 2)
{
  rowIdn = 26;
}
else if (tmp == -5 && verticalAngle < -5)
{
  rowIdn = 5;
}
else if (tmp == -6)
{
  rowIdn = 4;
}
else if (tmp == -8)
{
  rowIdn = 3;
}
else if (tmp == -10)
{
  rowIdn = 2;
}
else if (tmp == -15)
{
  rowIdn = 1;
}
else if (tmp == -25)
{
  rowIdn = 0;
}
else
{
  continue;
}
```

Admittedly, it's rather coarse and redundant, but it worked well in the original LeGO-LOAM. I'm still checking the code to see if there is anything I forgot to change.

This is my `loam_config.yaml` file:

```yaml
# RS-32
laser:
    num_vertical_scans: 32
    num_horizontal_scans: 1800
    ground_scan_index: 20
    vertical_angle_bottom: -25          # degrees
    vertical_angle_top: 15              # degrees
    sensor_mount_angle: 0               # degrees
    scan_period: 0.1                    # seconds
```

So far they are all the changes I made to adapt to the new LiDAR, but the result is poor and a lot of points are missing. There are not enough points to extract feature and to generate accurate odometry results, thus the map cannot be built.
I'm still checking the code to see if there's still anything related to a new LiDAR implementation. It would be really helpful if you could give me a hint about this, thanks in advance!

Best wishes.
