### ISSUE TITLE
Ouster 64 cloud projection

### ISSUE THREAD

**Issue by brunoeducsantos** [facontidavide/LeGO-LOAM-BOR#8]
Hi @facontidavide ,
Thanks for the improvements on Lego-LOAM performance.
Regarding the projection of point cloud for 64 beams, is there any plans to implement that?
Thanks,
Bruno

**Comment by facontidavide** [comment]
I don't see why it would not work, given the right configuration. Have you tried?

**Comment by brunoeducsantos** [comment]
Yes. I tried . For the this lidar: https://ouster.com/products/os1-lidar-sensor
I tried the following configuration in yaml file:
```
   laser:
        num_vertical_scans: 64
        num_horizontal_scans: 1024
        ground_scan_index: 15
        vertical_angle_bottom: -16.6          # degrees
        vertical_angle_top: 16.6              # degrees
        sensor_mount_angle: 0               # degrees
        scan_period: 0.1                    # seconds

```

Does it make sense?
